CSCI-GA-2820-FA24-003/inventory

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
Made the following changes
- Created a model for an Inventory of an item
- Implemented basic Serialize and Deserialize methods for Inventory model
- Created an InventoryFactory that creates an Inventory model object
- Wrote test case for creating inventory model object
> Added Inventory model

- service/routes.py
- tests/test_routes.py
- Added the create_inventory endpoint in `routes.py`
- Added test cases for create_inventory endpoint
> Add create inventory

- service/routes.py
- tests/test_routes.py
- Added READ  endpoint in "route.py".
- Modified CREATE endpoint in "route.py" to return the Location for created inventory item.
- Added test case for READ endpoint.
- Modified test case for CREATE endpoint.
> Added READ inventory endpoint

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
Changes Made:
- Added find_by_restock_level, find_by_quantity, find_by_condition, find_by_name methods in `models.py`
- Added test cases for find, find_by_restock_level, find_by_quantity, find_by_condition, find_by_name methods in `test_models.py`
- Added List Inventories method in `routes.py`
- Added test cases for List Inventories in `test_routes.py`
> Added List Inventories endpoint

- service/routes.py
- tests/test_routes.py
- Added UPDATE endpoint in "route.py".
- Added test case for UPDATE endpoint.
> Added UPDATE inventory endpoint

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
- Modified model schema to support detecting bad request.
- Added lots of test cases to test CRUD, error handling, model schema, QUERY endpoint and so on. 
- Modified code format and added some docstring to meet PEP8 Python standard.
- Fixed a bug in LIST endpoint.
> Improved Test Coverage and Code Standard

- service/routes.py
- Added the return of the root URL with JSON information, including endpoint details.
> Update Root URL

- service/routes.py
- tests/test_routes.py
- Fixed bugs in the List endpoint in route.py
- Added 2 test cases for List endpoint in test_routes.py
> Added Query to the List Endpoint

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_routes.py
- Added a Start Process for Restocking in "routes.py"
- Add a new attribute for inventory model to represent its restocking status.
- Added test case for the Start Process.
> Added a function to Start Restocking

- Dockerfile
- Makefile
- k8s/deployment.yaml
- k8s/ingress.yaml
- k8s/postgres/configmap.yaml
- k8s/postgres/pvc.yaml
- k8s/postgres/secret.yaml
- k8s/postgres/service.yaml
- k8s/postgres/statefulset.yaml
- k8s/pv.yaml
- k8s/service.yaml
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
**Set up local Kubernetes cluster**
1. Modified 'make cluster' command to Makefile
2. Configured proper yaml files for k8s and postgres directories
3. Deployed database as a StatefulSet, and change the database name to 'inventory'
4. Add \health endpoint
5. Deploy service to local kubernetes cluster, make sure it works, ensure ingress can access application
> Kubernetes

- .github/workflows/ci.yml
Modifications to ci.yaml file:
- Change the postgres image to postgres:15-alpine
- change the database URI
- Expose the ports of database
- Add Flask app to environment variables
> Changes to ci.yml

- service/routes.py
- service/static/index.html
- tests/test_routes.py
Made the following change:
1. Created a `static` folder under `service` folder to hold static assets.
2. Add an index.html in `static` folder for the index page UI.
3. Modify routes.py so the root url becomes the UI.
> add ui page

- service/models.py
- service/routes.py
- tests/test_models.py
- tests/test_routes.py
- Added find_by_restocking_available function.
- Added test cases for find_by_restocking_available.
> Added Search Functionality for stocking_available

- features/inventory.feature
- Added Create UI Behaviour and its test case in .feature and web_steps.
> Added Create UI 

- features/inventory.feature
- features/steps/inventories_steps.py
- Added Read UI Behaviour and its test case in .feature file, web_steps, and inventories_steps file.
> Added Read UI 

- features/inventory.feature
- features/steps/inventories_steps.py
- Added Update UI Behaviour and its test case in .feature and web_steps.
> Added Update UI 

- features/inventory.feature
- features/steps/inventories_steps.py
- Added Delete UI Behaviour and its test case in .feature and web_steps files.
> Added Delete UI

- features/inventory.feature
- service/static/index.html
- service/static/js/rest_api.js
- Added List UI Behaviour and its test case in .feature and web_steps files.
- Fixed bugs in homepage.
> Added List UI

- features/inventory.feature
- service/static/index.html
- service/static/js/rest_api.js
- Added Query UI Behaviour and its test case in .feature and web_steps files.
- Fixed bug in homepage.
> Added Query UI

- features/inventory.feature
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/test_routes.py
- Added a Stop Process for Restocking in "routes.py"
- Added test case for the Stop Process.
> Added a function to Stop Restocking 

- features/inventory.feature
- service/routes.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/test_routes.py
Made following features:
- Added Action UI Behaviour and its test case in .feature and web_steps files.
- Added 2 buttons in homepage.
- Added functions for buttons in rest_api.js file.
> Added Action UI 

- .tekton/pipeline.yaml
- Added behave test for the CD pipeline in the pipeline.yaml
> Added behave test for the CD pipeline
